# Generated by Django 2.2.5 on 2019-10-02 17:06

from django.db import migrations


def create_users(apps, schema_editor):
    User = apps.get_model('users', 'User')

    User.objects.create(name='User 1')
    User.objects.create(name='User 2')
    User.objects.create(name='User 3')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
