# Generated by Django 2.2.5 on 2019-10-02 17:15

from django.db import migrations


def create_quizzes(apps, schema_editor):
    Answer = apps.get_model('quizapp', 'Answer')
    Question = apps.get_model('quizapp', 'Question')
    Quiz = apps.get_model('quizapp', 'Quiz')

    answer1 = Answer.objects.create(content='Yes')
    answer2 = Answer.objects.create(content='No')
    question = Question.objects.create(content='Are you human?', correct_answer=answer1)
    question.answers.add(answer1)
    question.answers.add(answer2)
    quiz = Quiz.objects.create(title='Test quiz')
    quiz.questions.add(question)


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_quizzes),
    ]
